name: Supabase Keep Alive (chesmi-training)

on:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase REST API with anon key
        run: |
          curl -I https://xbjatqnptzdmxsikvhsq.supabase.co/rest/v1/ \
            -H "apikey:'SUPABASE_CLIENT_API_KEY'"
